@url = "http://localhost:3000/"

GET http://localhost:3000/routes HTTP/1.1

###

GET http://localhost:3000/routes/bcc205b6-7f13-4fe4-b7ac-6e49a0156a09 HTTP/1.1

###

POST http://localhost:3000/routes HTTP/1.1
Content-Type: application/json

{
    "title": "Flight to Nigeria",
    "time": "10pm", 
    "price": "300", 
    "date": "12-08-2022"
}

###
PUT http://localhost:3000/routes/6007dcbe-050c-4b27-90c3-da6930937af5 HTTP/1.1
Content-Type: application/json

{
    "title": "Flight to Germany",
    "time": "3pm", 
    "price": "75000", 
    "date": "25-05-2022"
}

###
DELETE http://localhost:3000/routes/bcc205b6-7f13-4fe4-b7ac-6e49a0156a09 HTTP/1.1

